import connectDB from "../lib/db.js";
import { config } from "dotenv";
import Product from "../models/product.model.js";
config();

const products = [
  {
    name: "React for Beginners",
    price: 450000,
    image: "https://via.placeholder.com/300x200",
    description:
      "Learn the fundamentals of React.js and build modern web applications.",
    shortDescription: "React basics and components",
    rating: 4.5,
    isSuggested: true,
    category: "6873728ed42adef51a81e986",
    viewedByUsers: [],
  },
  {
    name: "Advanced JavaScript",
    price: 750000,
    image: "https://via.placeholder.com/300x200",
    description: "Deep dive into advanced JavaScript topics and patterns.",
    shortDescription: "Deep JS knowledge",
    rating: 4.7,
    isSuggested: false,
    category: "6873728ed42adef51a81e986",
    viewedByUsers: [],
  },
  {
    name: "Flutter Mobile App Development",
    price: 950000,
    image: "https://via.placeholder.com/300x200",
    description:
      "Create beautiful native apps for Android and iOS using Flutter.",
    shortDescription: "Cross-platform Flutter course",
    rating: 4.3,
    isSuggested: true,
    category: "687372768eb88e71a4cacd8f",
    viewedByUsers: [],
  },
  {
    name: "Python for Data Science",
    price: 600000,
    image: "https://via.placeholder.com/300x200",
    description: "Analyze and visualize data using Python, NumPy, and Pandas.",
    shortDescription: "Data with Python",
    rating: 4.6,
    isSuggested: false,
    category: "687372768eb88e71a4cacd90",
    viewedByUsers: [],
  },
  {
    name: "Photoshop Essentials",
    price: 380000,
    image: "https://via.placeholder.com/300x200",
    description: "Learn the essential tools and workflows of Adobe Photoshop.",
    shortDescription: "Photoshop basics",
    rating: 4.2,
    isSuggested: true,
    category: "687372768eb88e71a4cacd91",
    viewedByUsers: [],
  },
  {
    name: "SEO & Digital Marketing Masterclass",
    price: 870000,
    image: "https://via.placeholder.com/300x200",
    description: "Master search engine optimization and digital strategies.",
    shortDescription: "Boost your marketing",
    rating: 4.4,
    isSuggested: true,
    category: "687372768eb88e71a4cacd92",
    viewedByUsers: [],
  },
  {
    name: "UX Design Fundamentals",
    price: 540000,
    image: "https://via.placeholder.com/300x200",
    description: "Understand user-centered design, wireframing, and testing.",
    shortDescription: "Design great experiences",
    rating: 4.1,
    isSuggested: false,
    category: "687372768eb88e71a4cacd93",
    viewedByUsers: [],
  },
  {
    name: "Ethical Hacking & Cybersecurity",
    price: 1080000,
    image: "https://via.placeholder.com/300x200",
    description:
      "Protect networks and systems through ethical hacking techniques.",
    shortDescription: "Hack the right way",
    rating: 4.8,
    isSuggested: true,
    category: "687372768eb88e71a4cacd94",
    viewedByUsers: [],
  },
  {
    name: "Intro to Machine Learning",
    price: 990000,
    image: "https://via.placeholder.com/300x200",
    description: "Build and train machine learning models using scikit-learn.",
    shortDescription: "Learn ML basics",
    rating: 4.5,
    isSuggested: false,
    category: "687372768eb88e71a4cacd95",
    viewedByUsers: [],
  },
  {
    name: "Excel for Finance",
    price: 620000,
    image: "https://via.placeholder.com/300x200",
    description: "Master Excel formulas, pivot tables, and financial models.",
    shortDescription: "Finance with Excel",
    rating: 4.3,
    isSuggested: true,
    category: "687372768eb88e71a4cacd96",
    viewedByUsers: [],
  },
  {
    name: "Goal Setting for Success",
    price: 300000,
    image: "https://via.placeholder.com/300x200",
    description:
      "Learn how to set and achieve meaningful goals in life and work.",
    shortDescription: "Achieve your dreams",
    rating: 4.0,
    isSuggested: false,
    category: "687372768eb88e71a4cacd97",
    viewedByUsers: [],
  },
  {
    name: "Node.js & Express Backend",
    price: 850000,
    image: "https://via.placeholder.com/300x200",
    description: "Create REST APIs using Node.js and Express.",
    shortDescription: "Backend development",
    rating: 4.6,
    isSuggested: true,
    category: "6873728ed42adef51a81e986",
    viewedByUsers: [],
  },
  {
    name: "Kotlin for Android",
    price: 780000,
    image: "https://via.placeholder.com/300x200",
    description: "Build Android apps using Kotlin and Android Studio.",
    shortDescription: "Modern Android development",
    rating: 4.4,
    isSuggested: false,
    category: "687372768eb88e71a4cacd8f",
    viewedByUsers: [],
  },
  {
    name: "Deep Learning with TensorFlow",
    price: 1200000,
    image: "https://via.placeholder.com/300x200",
    description: "Train deep neural networks using TensorFlow.",
    shortDescription: "Neural networks hands-on",
    rating: 4.7,
    isSuggested: true,
    category: "687372768eb88e71a4cacd95",
    viewedByUsers: [],
  },
  {
    name: "Accounting Basics",
    price: 500000,
    image: "https://via.placeholder.com/300x200",
    description: "Understand key accounting principles and practices.",
    shortDescription: "Master the balance sheet",
    rating: 4.2,
    isSuggested: false,
    category: "687372768eb88e71a4cacd96",
    viewedByUsers: [],
  },
  {
    name: "Figma for UI Design",
    price: 400000,
    image: "https://via.placeholder.com/300x200",
    description: "Design beautiful interfaces and collaborate using Figma.",
    shortDescription: "Design in the browser",
    rating: 4.4,
    isSuggested: true,
    category: "687372768eb88e71a4cacd93",
    viewedByUsers: [],
  },
  {
    name: "Startup Marketing Essentials",
    price: 680000,
    image: "https://via.placeholder.com/300x200",
    description: "Grow your startup with proven digital marketing tactics.",
    shortDescription: "Marketing for growth",
    rating: 4.3,
    isSuggested: false,
    category: "687372768eb88e71a4cacd92",
    viewedByUsers: [],
  },
  {
    name: "Cyber Threat Intelligence",
    price: 1150000,
    image: "https://via.placeholder.com/300x200",
    description: "Identify and respond to emerging cybersecurity threats.",
    shortDescription: "Stay ahead of hackers",
    rating: 4.6,
    isSuggested: true,
    category: "687372768eb88e71a4cacd94",
    viewedByUsers: [],
  },
  {
    name: "Illustrator for Beginners",
    price: 350000,
    image: "https://via.placeholder.com/300x200",
    description:
      "Create vector graphics and digital art with Adobe Illustrator.",
    shortDescription: "Intro to vector art",
    rating: 4.1,
    isSuggested: false,
    category: "687372768eb88e71a4cacd91",
    viewedByUsers: [],
  },
  {
    name: "Time Management Mastery",
    price: 420000,
    image: "https://via.placeholder.com/300x200",
    description: "Boost productivity and manage your time effectively.",
    shortDescription: "Work smarter, not harder",
    rating: 4.0,
    isSuggested: true,
    category: "687372768eb88e71a4cacd97",
    viewedByUsers: [],
  },
];

try {
  await connectDB();
  await Product.deleteMany();
  await Product.insertMany(products);
  console.log("Database seeded successfully");
  process.exit();
} catch (error) {
  console.log("Error seeding database:", error);
  process.exit(1);
}
